<template>
  <div>
    <el-button>Default</el-button>
    <el-button type="primary">Primary</el-button>
    <el-button type="success">Success</el-button>
    <el-button type="info">Info</el-button>
    <el-button type="warning">Warning</el-button>
    <el-button type="danger">Danger</el-button>
    <el-icon><Aim /></el-icon>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>

  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  <div>
    <el-button>Default</el-button>
  </div>
  

</template>

<script setup lang="ts">

</script>

<style scoped>

</style>